name: TDS Caching Task
on: [push, workflow_dispatch]

jobs:
  cache-prime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Prime Step
        id: cache-step
        uses: actions/cache@v4
        with:
          path: data.txt
          key: cache-9958c9b

      - name: prime-cache-9958c9b
        id: prime-cache-9958c9b
        run: |
          echo "Cache Hit: ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Create data if miss
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: echo "content" > data.txt
